### ISSUE TITLE
TypeError when using &&

### ISSUE THREAD

**Issue by dodekeract** [hyperapp/hyperapp#92]
I wanted to remove a node depending on the value of `model.isVisible`.

`TypeError: undefined is not an object (evaluating 'node.data')`

---

## Broken Code

```javascript
export default ({isVisible}) =>
	{isVisible && <div>Example!</div>}
```

## Workaround

```javascript
export default ({isVisible}) =>
	{isVisible ? <div>Example!</div> : <div></div>}
```

---

## Problem

In React the broken version should just work, I think it's a cleaner solution (and actually it doesn't create a DOM Node). I'm assuming this is a bug?

**Comment by dodekeract** [comment]
Nevermind, turned out to be caused by something else. `&&` works properly.

**Comment by jbucaran** [comment]
@dodekeract Actually, this led me to discover a bug.
```jsx

app({ 
    model: { isVisible: false }, 
    view: model => 
        <div>
            {model.isVisible && <div>Example!</div>}
        </div>
})
```

Will render `false`.

The reason is because our vdom treats primitive values as valid textnodes. The solution is to not render bools.

I made it the way it is now, because it was bothering me having to

```jsx
<div>model.boolean.toString()</div>
```

But now I understand why we don't want to render booleans.

**Comment by jbucaran** [comment]
On the other hand, 

```jsx
model.isVisible ? <div>Example!</div> : ""
```

works too. So, we can have bools as text nodes and do like in the example above.

**Comment by dodekeract** [comment]
But then we'll have to use the ternary operator even though the decision isn't really ternary.

**Comment by jbucaran** [comment]
I'm not really sure if 

```
model.isVislble && <div>ok</div>
```

is better or more convenient than

```
model.isVisible ? <div>Example!</div> : ""
```

In JavaScript:

```
var a = someBool && myObject
```

will store either myObject or false in `a`. So `model.isVislble && <div>ok</div>` is creating either:

```
vnode("div", {}, [h("div", {}, "ok")])
```
or
```
vnode("div", {}, [false])
```

Why should the vdom skip a boolean?

**Comment by dodekeract** [comment]
Why should vdom render a boolean as text? It's neither a string nor a node.

**Comment by jbucaran** [comment]
That's a good question too!

What should we do?

**Comment by selfup** [comment]
`(Array.isArray(variable) && typeof(variable[0]) === "boolean") ? [] : variable;`

Something like that?

**Comment by jbucaran** [comment]
I find the approach:

```jsx
model.isVisible ? <div>Example!</div> : ""
```

simpler to implement, maintain and also more readable than using && or ||. 

If you have a single vnode tree that you want on/off, && or || might seem convenient, but what if you actually want to show something?

```jsx
model.isGood ? <div>Good</div> : <div>Bad</div>
```

In that case you'll use the ternary operator. I'd rather use the ternary operator always.

I had this issue myself when I first started React. I found the `bool && Component` pattern often, but it left me scratching my head often as well as my expressions became more and more complex.

I find the ternary operator the most clear (other than the fact that's using arbitrary ? and : characters).

**Comment by tunnckoCore** [comment]
It's better to not support boolean values. If they need to output them they can `.toString()`? But yea `?` looks better to be used.

**Comment by dodekeract** [comment]
@jbucaran Of course, the ternary operator is useful too. I use both all the time, depending on what exactly I want to achieve.

I still think the use-case for displaying a boolean is far more limited though. Especially since it isn't even language-aware. It'll display it in English all the time, which makes it useless for 75+% of the world. In addition to that I think returning `false` is probably the most explicit thing you can do to communicate "please don't render this".

**Comment by jbucaran** [comment]
Related:
* https://github.com/substack/hyperx/issues/42

**Comment by jbucaran** [comment]
I think this is fixed now.

https://github.com/hyperapp/hyperapp/commit/7a60a8f18163c31ec74c174c18337b7a31ae2dfb

@dodekeract Please check 🙏

**Comment by dodekeract** [comment]
I can still reproduce this with `<div>{null && <div>test</div>}</div>`. So it seems to be fixed for `false`, but not for `null`.

**Comment by jbucaran** [comment]
@dodekeract Correct, null is not handled! I'll add it soon 👍.

**Comment by jbucaran** [comment]
Fixed in https://github.com/hyperapp/hyperapp/commit/e47017ae2e238fce675b3aad29fb9c24affe1329
